name: cron
on:
    schedule:
        - cron: '0 0 * * 1'
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: npx npm-check-updates --doctor --upgrade
            - name: Set up Git
              run: |
                  git config --global user.name "${GITHUB_ACTOR}"
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            - name: Update Dependencies
              run: |
                  npx npm-check-updates --doctor --upgrade
                  npm audit fix
                  git add -u :/
                  set +e
                  git commit -m "update dependencies"
                  echo "SKIP=$?" >> $GITHUB_ENV
            - name: Git Push
              if: env.SKIP != '1'
              run: |
                  git push
                  git push origin ${{ env.VERSION }}
